import Head from 'next/head'
import Image from 'next/image'
import { Inter, Revalia } from '@next/font/google'
import styles from '../styles/Home.module.css'
import { Header } from '../src/components/Header/Header'
import { Heading } from '../src/components/Heading/Heading'
import { About } from '../src/components/About/About'
import { Technologies } from '../src/components/Technologies/Technologies'
import { Steps } from '../src/components/Steps/Steps'
import { Questions } from '../src/components/FAQ/FAQ'
import { Review } from '../src/components/Review/Review'
import { Gallery } from '../src/components/Gallery/Gallery'
import { Contact } from '../src/components/Contact/Contact'
import { Footer } from '../src/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page}>
        <Header/>
        <main className={styles.main}>
          <Heading />
          <About />
          <Technologies />
          <Steps />
          <Questions />
          <Review />
          <Gallery />
          <Contact />
        </main>
        <Footer/>
      </div>
    </>
  )
}



export default Home